import { HttpException, HttpStatus } from '@nestjs/common';

export class ApiErrorException extends HttpException {
  constructor(
    message: string,
    errorCode: string,
    statusCode: HttpStatus = HttpStatus.BAD_REQUEST,
    data?: any,
  ) {
    const response = {
      statusCode,
      message,
      error: errorCode,
      timestamp: new Date().toISOString(),
      ...(data && { data }),
    };

    super(response, statusCode);
  }
}

export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_USER_ID = 'INVALID_USER_ID',

  UNAUTHORIZED = 'UNAUTHORIZED ',

  DUPLICATE_EMAIL = 'DUPLICATE_EMAIL',
  INVALID_EMAIL = 'INVALID_EMAIL',
  EMAIL_REQUIRED = 'EMAIL_REQUIRED',

  INVALID_PASSWORD = 'INVALID_PASSWORD',
  PASSWORD_MISMATCH = 'PASSWORD_MISMATCH',
  PASSWORD_REQUIRED = 'PASSWORD_REQUIRED',

  VALIDATION_ERROR = 'VALIDATION_ERROR',
  MISSING_FIELD = 'MISSING_FIELD',
  DATABASE_ERROR = 'DATABASE_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',

  INVALID_ACCOUNT_ID = 'INVALID_ACCOUNT_ID',
  DUPLICATE_ACCOUNT = 'DUPLICATE_ACCOUNT',
  ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND',
  INVALID_CURRENCY = 'INVALID_CURRENCY',
  INVALID_ACCOUNT_TYPE = 'INVALID_ACCOUNT_TYPE',

  REFRESH_TOKEN_INVALID = 'REFRESH_TOKEN_INVALID',

  CATEGORIES_NOT_FOUND = 'CATEGORIES_NOT_FOUND',

  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR ',

  TRANSACTIONS_NOT_FOUND = 'TRANSACTIONS_NOT_FOUND',
  TRANSACTION_NOT_FOUND = 'TRANSACTION_NOT_FOUND',
  INVALID_TRANSACTION_ID = 'INVALID_TRANSACTION_ID ',

  GROUP_NOT_FOUND = 'GROUP_NOT_FOUND',
  INVALID_GROUP_ID = 'INVALID_GROUP_ID',
}
